### ISSUE TITLE
/etc/modprobe.d/CIS.conf is not being created

### ISSUE THREAD

**Issue by mjdavies** [oguya/cis-ubuntu-14-ansible#10]
Hello

I'm running the initial check, but the checks are failing when it's trying to create the /etc/modprobe.d/CIS.conf file.

TASK: [cis | 7.5 Uncommon Network Protocols] **********************************
ok: [railsstage4] => {
    "msg": "**\* It is recommended to disable unused protocols in the kernel"
}

TASK: [cis | Check if /etc/modprobe.d/CIS.conf exists] ************************
ok: [railsstage4]

TASK: [cis | Create /etc/modprobe.d/CIS.conf] *********************************
changed: [railsstage4]

TASK: [cis | 7.5.1 Disable DCCP (Not Scored)] *********************************
failed: [railsstage4] => {"failed": true, "rc": 257}
msg: Destination /etc/modprobe.d/CIS.conf does not exist !

FATAL: all hosts have already failed -- aborting

Not really sure why it's not being created, the playbook looks fine.

Any ideas?

**Comment by oguya** [comment]
When doing initial checks and `/etc/modprobe.d/CIS.conf` doesn't exists, `lineinfile` module would fail because it can't find the destination file to use.

Otherwise, if `/etc/modprobe.d/CIS.conf` exists, and you rerun the checks, it shouldn't fail!

**Comment by mjdavies** [comment]
Hi oguya

I'm a bit confused

If it fails when you're doing the initial checks, because CIS.conf doesn't exist, what are you supposed to do to make the checks not fail?

Is this expected behaviour?

An earlier test failed as NTP wasn't installed, so I installed that to get past that block in the checks, am I supposed to install something else now?

**Comment by oguya** [comment]
when doing checks/dry-run using `--check`, `lineinfile` module expects the destination file to exist otherwise it fails.
So if you run the playbook, the `/etc/modprobe.d/CIS.conf` file will be created and the subsequent tasks depending on it won't fail.

I think you should also take note of dependencies. For instance, for you to edit NTP's `/etc/ntp.conf` - [in section 6.5](https://github.com/oguya/cis-ubuntu-14-ansible/blob/master/roles/cis/tasks/section-06-level-1.yml#L78) - you should first install NTP.

**Comment by mjdavies** [comment]
Ahh, I think I've got it now!!

The checks are to be run in order to check that the normal rum will work, is that it?

IE, it will check if NTP is there, if it isn't, the check will fail?

**Comment by oguya** [comment]
Yes, you are right. I think you now get the concept.
